import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../components/Navbar'
import 'bootstrap/dist/css/bootstrap.css';
import HeroSection from '../components/HeroSection'
import FilterSection from '../components/FilterSection'
import MainContainer from '../components/SelectContainer'
import CardSection from '../components/CardSection'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
        rel="stylesheet"
        href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"
        />
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
      </Head>
      <div className='home_container'>
        <Navbar />
        <HeroSection />
        <FilterSection />
        <div class="main_container_desktop">
          <MainContainer />
          <CardSection />
        </div>
      </div>
    </>
  )
}
